### ISSUE TITLE
Classes not working as expected

### ISSUE THREAD

**Issue by etherealbacon** [stevewoolcock/WrenSharp#1]
Hello,

Thanks for all the effort that has gone into this so far.

The following is example code from the Wren website:
```
System.print("hello main")
System.print("hello matt")


class Unicorn {
  construct new(name) {
    System.print("My name is " + name + " and I am red.")
  }
}

var dave = Unicorn.new("Dave")
```

I am plugging this into the VM and getting the following:

```
[Backend.services.ScriptingService :: InterpretFromDBID] Compile: Error at 'Unicorn': Module variable is already defined.
[Backend.services.ScriptingService :: InterpretFromDBID]    at WrenSharp.WrenVM.Interpret(String module, String source, Boolean throwOnFailure) in C:\Users\nethr\Documents\Projects\WrenSharp\WrenSharp.Core.Shared\WrenVM.cs:line 307
   at Backend.services.ScriptingService.InterpretFromDBID(String ID) in C:\Users\nethr\Documents\Projects\SinServ\Backend\services\ScriptingService.cs:line 178
  ```
   
   
   This is using the standard vm code as per the readme:
   
   ```  var moduleProvider = new ModuleLoader();
  var output = new ScriptingConsoleOutput();
  var config = new WrenVMConfiguration()
  {
      LogErrors = true,
      ErrorOutput = output,
      WriteOutput = output,
      ModuleProvider = moduleProvider,
  };

  WrenSharpVM = new WrenSharpVM(config);
  ```
   
   
   I may well be doing something silly but not having much luck. Running the same code in a text file via the wren_cli produces the expected output.
   
  ```
  $ wren_cli.exe main.wren
hello main
hello matt
My name is Dave and I am red.

```
   
   Thanks again!

**Comment by stevewoolcock** [comment]
Glad you figured it out!
